### PR TITLE
Revert "ices/86784.sh: fixed with no errors"

### PR DESCRIPTION
**Pull request by hellow554**
Ths ICE is not fixed upstream, let's try to reintroduce it again
cc https://github.com/rust-lang/glacier/pull/902

This reverts commit 54de8af280637c6a430204371935bfe577c4a582.

### CODE REVIEW

**Comment by hellow554** [comment]
It seems that it still ICEs on the testbench.
@Alexendoo should we give it a try?

**Comment by Alexendoo** [comment]
I think this one was a little spurious, I'll re-run it a couple times and if it's all green then yeah let's add it back

**Review by Alexendoo — APPROVED** [review]
It passed 3 times, should be good 👍

**Comment by hellow554** [comment]
Thanks!
Would you mind pinging me when the test will pass again without actually be fixed? I try to keep an eye on the original issue (https://github.com/rust-lang/rust/issues/86784) as well.

**Comment by Alexendoo** [comment]
Sure, will do

**Pull request merged**
