### PR TITLE
add more ices 

### PR DESCRIPTION
**Pull request by matthiaskrgr**
https://github.com/rust-lang/rust/issues/101739
https://github.com/rust-lang/rust/issues/101852
https://github.com/rust-lang/rust/issues/101940
https://github.com/rust-lang/rust/issues/101962
https://github.com/rust-lang/rust/issues/101696

### CODE REVIEW

**Comment by JohnTitor** [comment]
https://github.com/rust-lang/rust/pull/101841 will remove save-analysis and I think we don't have to track ICEs related to it anymore, could you drop #101739?

**Comment by matthiaskrgr** [comment]
we can just remove the flag from the respective tests and keep them for additional coverage imo

**Comment by JohnTitor** [comment]
Why doesn't it belong to rust-lang/rust but here?

**Comment by matthiaskrgr** [comment]
It belongs in both? :upside_down_face: 
Some of the save-analysis tests might eventually get removed so it will be nice to still have them somewhere in case rustc starts crashing on one some of the tests again.

**Comment by JohnTitor** [comment]
> It belongs in both? 🙃 Some of the save-analysis tests might eventually get removed so it will be nice to still have them somewhere in case rustc starts crashing on one some of the tests again.

Hmm, I don't think "somewhere" is here, the problem is that checking the past/potential ICEs is just a personal project while the main repo tests them as CI, and separating the testing system increases the maintenance burden and introduces duplicate coverage. If you seriously think we should keep them as tests, you could argue and add them on the main repo, or make it an official project so that we could check them while the Rust project lives.

**Comment by matthiaskrgr** [comment]
There is already a call for checking past/potential ICES: https://github.com/rust-lang/glacier/issues/1156

>main repo tests them as CI
This is a moot point because unfortunately tests also get removed from the main repo.
I would guess I have already found 10-20 ICEs in testcases that were once part of the main repo but have been removed since.

I already have my way of extracting half a million .rs files from the rustc repo and use this as a testset but checking all of that for ICEs can take a couple of days (or weeks) while glacier/fixed takes maybe a couple minutes to an hour.
So for me this is a matter of efficiency since glacier/fixed is more ice-y.

Right, we can also make the entire glacier project redundant by adding ICEs directly into the main rust repo which would have the benefit of directly "failing" the tests whenever one of the crashes is fixed. :thinking:

**Pull request closed without merging**
