### PR TITLE
15694 is now fixed

### PR DESCRIPTION
**Pull request by Alexendoo**
rust-lang/rust#15694

### CODE REVIEW

**Comment by JohnTitor** [comment]
But I'm not sure we should remove the ICEs, see the issue: #154

**Comment by Alexendoo** [comment]
I can move it to a different dir if you prefer

We can also leave the decision until later and bring them all back at that point if it's decided to keep it in tree

For this one I went with the current precedent e.g. 7a2f7a1320bbe072b3dd73e341c9ef80645ebc34

**Comment by JohnTitor** [comment]
Okay, so it's worth to create the dir named `fixed-ices` or something and put it there, I think.

**Comment by Alexendoo** [comment]
Changed it to be in a directory

**Pull request merged**
