### PR TITLE
ICEs from rust-lang/rust

### PR DESCRIPTION
**Pull request by araruna**
Proposing ICE examples from issues 82335, 82836, 83801, 84020, 85113 and 85103.

### CODE REVIEW

**Comment by araruna** [comment]
One of them requires the `aarch64-apple-darwin` target. Is there a way to express this constraint in the script?

**Comment by Alexendoo** [comment]
Perhaps you could change the rust-toolchain file to be the new toml version that includes it in `targets` https://rust-lang.github.io/rustup/overrides.html#the-toolchain-file

**Comment by araruna** [comment]
> Perhaps you could change the rust-toolchain file to be the new toml version that includes it in `targets` https://rust-lang.github.io/rustup/overrides.html#the-toolchain-file

Yes, but what I mean is to be able to run it in the CI of this repo. I'm able to reproduce the ICE in my machine bu not here...

I see how I can use a custom `rustc` command to change the target, but not how to guarantee that said target is available in the CI.

**Comment by Alexendoo** [comment]
I mean the file in this repo https://github.com/rust-lang/glacier/blob/master/rust-toolchain, if you add `aarch64-apple-darwin` as a target it should be installed automatically for other contributors and CI

**Comment by araruna** [comment]
> I mean the file in this repo https://github.com/rust-lang/glacier/blob/master/rust-toolchain, if you add `aarch64-apple-darwin` as a target it should be installed automatically for other contributors and CI

Oooohh, I see... Now I get it. Sorry...

Thank you for your suggestion, I'm going to look into that.

**Comment by fanninpm** [comment]
Have you had any time to revisit this?

**Comment by araruna** [comment]
I'm sorry... Not yet. Are you planning to take it over?

I'm very busy right now, so if that's the case you can totally do it. If not, I'm afraid I'll only have the time late next week.

**Comment by fanninpm** [comment]
@JohnTitor Please take a look at 3ba6de7. I was able to get it to ICE on Manjaro just by installing the `aarch64-apple-darwin` toolchain.

**Review by JohnTitor — APPROVED** [review]

**Comment by JohnTitor** [comment]
Thanks!

**Pull request merged**
