### PR TITLE
Add up to 6 ICEs

### PR DESCRIPTION
**Pull request by fanninpm**
71546 might need some work done on the `main()` function.

### CODE REVIEW

**Comment by JohnTitor** [comment]
Overall looks good, could you drop 71805.rs since the issue has been fixed already and add a new line to the end of each file?

**Comment by JohnTitor** [comment]
Also needs a rebase.

**Comment by fanninpm** [comment]
Do I need to squash commits?

**Comment by JohnTitor** [comment]
> Do I need to squash commits?

I'd prefer so.

**Comment by fanninpm** [comment]
Are 70934 and 71798 fixed as well?

**Comment by JohnTitor** [comment]
Oops, sorry! I mistook 71798 for 71805, the later hasn't been fixed yet.

**Comment by fanninpm** [comment]
Glad to help! Where do I go for further questions unrelated to this PR?

**Comment by JohnTitor** [comment]
> Where do I go for further questions unrelated to this PR?

If it's related to glacier, the issue tracker is one of the good places. If related to Rust itself, then we have some places, e.g. Discord, Discourse, Zulip, etc.

**Pull request merged**
