### PR TITLE
Add some ICEs

### PR DESCRIPTION
**Pull request by Alexendoo**
This covers 2 pages of issues, with many skipped that I either couldn't reproduce or had extra requirements (full crate, incremental builds, etc)

### CODE REVIEW

**Comment by JohnTitor** [comment]
Hmm, it's odd. Travis says permission denied and returns an error.

**Comment by JohnTitor** [comment]
I'm not sure but probably it's related to `ices/63900.sh`?

**Comment by Alexendoo** [comment]
I think it's actually that I didn't commit the .sh as executable, I'll fix that

**Comment by Alexendoo** [comment]
That fixed that one, the remaining error would be covered by #156

**Comment by JohnTitor** [comment]
Could you rebase it to make sure of passing the CI?

**Comment by Alexendoo** [comment]
Sure thing. Rebased it

**Pull request merged**
